### ISSUE TITLE
 Learn from fundamentals of HTML and semantics course

### ISSUE THREAD

**Issue by Prapti-Patel** [codecyclecommunity/learning-at-codecycle#1141]
### Purpose
- [x] To learn fundamentals of HTML and semantics course 
### Implement
- [x] Update issue (title, assignee, labels, projects, purpose, discovery, implement, measure)
- [x] Learn from [HTML Fundamentals Course](https://app.pluralsight.com/library/courses/html-fundamentals/table-of-contents)
- [x] Learn from [Semantic HTML](https://app.pluralsight.com/library/courses/semantic-html/table-of-contents)
### Measure
- [ ] Validate basic concepts of HTML
- [ ] Course should be completed

**Comment by beingminimal** [comment]
given link in this task is working.. please clarify which link is not working for you?

**Comment by Prapti-Patel** [comment]
@beingminimal it is working sir.

**Comment by Prapti-Patel** [comment]
@beingminimal I learn basic concept of HTML. please review sir.

**Comment by beingminimal** [comment]
Approved. Close this task and continue with your learning journey.

**Comment by sakshi-suthar** [comment]
hey @Prapti-Patel have you completed your CSS positioning issue?
