### ISSUE TITLE
 Learn CSS up to Flex (000 to 009)

### ISSUE THREAD

**Issue by Prapti-Patel** [codecyclecommunity/learning-at-codecycle#1148]
### Purpose
- [x] To learn basics of CSS
### Implement
- [x] Update issue (title, assignee, labels, projects, purpose, discovery, implement, measure)
- [x] Learn 000 ([Learn CSS](https://web.dev/learn/css/)) to 009 ([Flex](https://web.dev/learn/css/flexbox/))
### Measure
- [x] All concepts learned in this task should be clear and understood.

**Comment by Prapti-Patel** [comment]
@beingminimal I completed it....Please review on this task.

**Comment by beingminimal** [comment]
Approved. Close this task and continue with your learning journey.

**Comment by sakshi-suthar** [comment]
@Prapti-Patel Hey have you done CSS positioning issue??
