### ISSUE TITLE
01 Learn Javsacript Loops

### ISSUE THREAD

**Issue by janikhushi** [codecyclecommunity/learning-at-codecycle#1150]
Add issue detail from learning documentation
### Purpose
- [x] To learn and practice Loops in Javascript
### Implement
- [x] Update issue (title, assignee, labels, projects, purpose, discovery, implement, measure)
- [x] Learn [Introduction](https://javascript.info/getting-started) 
- [x] Learn [Javascript Fundamentals](https://javascript.info/first-steps)
- [x] Practice each task available at the end of each section in Introduction and Javascript Fundamentals.
- [x] Create pyramid patterns using loops
Pattern 1
*
* * 
* * *
* * * *

Pattern 2
    *
   * *
  * * *
 * * * *
* * * * *
### Measure
- [x] Validate basic concepts of Javascript loops
- [x] Patterns created with advance looping.
### Additional info

**Comment by janikhushi** [comment]
@beingminimal sir , I am faceing the some error. can you please resolve it. 
![error](https://user-images.githubusercontent.com/124026907/225973303-f11fe6d4-6aab-4df2-81e8-40a399b271ed.png)

**Comment by janikhushi** [comment]
@beingminimal please review ...

**Comment by beingminimal** [comment]
#1158 Is this issue same?

**Comment by janikhushi** [comment]
@beingminimal  No sir, this is pattern issue and #1158 this is Calculator issue....

**Comment by beingminimal** [comment]
Approved. Close this task and continue with your learning journey.
