### ISSUE TITLE
02 Learn Javsacript Loops and functions

### ISSUE THREAD

**Issue by janikhushi** [codecyclecommunity/learning-at-codecycle#1158]
Add issue detail from learning documentation
### Purpose
- [x] To learn Loops and functions in Javascript
### Implement
- [x] Update issue (title, assignee, labels, projects, purpose, discovery, implement, measure)
- [x] Create calculator program with functions - add , subtract, multiply, divide.
### Measure
- [x] Validate basic concepts of Javascript loops and functions
- [x] Validate calculator program
### Additional info

**Comment by beingminimal** [comment]
Open the command line.
Set your username: git config --global user.name "FIRST_NAME LAST_NAME"
Set your email address: git config --global user.email "MY_NAME@example.com"

**Comment by janikhushi** [comment]
@beingminimal please review..

**Comment by beingminimal** [comment]
Please be clear with what should I review. Cannt see any PR for this issue

**Comment by beingminimal** [comment]
Approved. Close this task and continue with your learning journey.
