### ISSUE TITLE
 Learn CSS Positioning

### ISSUE THREAD

**Issue by Prapti-Patel** [codecyclecommunity/learning-at-codecycle#1159]
### Purpose
- [x] To learn use of Positioning in CSS
### Implement
- [x] Update issue (title, assignee, labels, projects, purpose, discovery, implement, measure)
- [x] Read [Learn CSS Positioning](https://ishadeed.com/article/learn-css-positioning/#intro) and implement same example in your branch.
### Measure
- [x] All positioning properties are clear and understood.

**Comment by Prapti-Patel** [comment]
@beingminimal Which example I have to implement for this task? example is not available in this link. so can you please tell me?

**Comment by beingminimal** [comment]
you have to implement same example available in the link.
