### ISSUE TITLE
Learn CSS upto Flex (000 to 009)

### ISSUE THREAD

**Issue by VasuDadhaniya** [codecyclecommunity/learning-at-codecycle#1163]
### Purpose
- [x] To learn basics of CSS

### Implement
- [x] Update issue (title, assignee, labels, projects, purpose, discovery, implement, measure)
- [x] Learn 000 ([Learn CSS](https://web.dev/learn/css/)) to 009 ([Flex](https://web.dev/learn/css/flexbox/))

### Measure
- [x] All concepts learned in this task should be clear and understood.

### Additional info

**Comment by VasuDadhaniya** [comment]
@beingminimal completed check it out sir

**Comment by beingminimal** [comment]
Approved. Close this task and continue with your learning journey.
