### ISSUE TITLE
 Learn from HTML cheatsheet

### ISSUE THREAD

**Issue by NILAYRAVAL** [codecyclecommunity/learning-at-codecycle#1164]
### Purpose
- [x] To remember all elements of HTML inside cheatsheet
### Implement
- [x] Update issue (title, assignee, labels, projects, purpose, discovery, implement, measure)
- [x] Learn [HTML Elements Cheatsheet](https://developer.mozilla.org/en-US/docs/Learn/HTML/Cheatsheet)
- [x] Learn [Semantics Cheatsheet](https://learn-the-web.algonquindesign.ca/topics/html-semantics-cheat-sheet/)
### Measure
- [x] Make sure you are aware with all elements available in Cheatsheet.
### Additional info

**Comment by NILAYRAVAL** [comment]
@beingminimal  completed please review my task.

**Comment by beingminimal** [comment]
Approved. Close this task and continue with your learning journey.
