### ISSUE TITLE
01 Learn Javsacript Loops

### ISSUE THREAD

**Issue by Rahul-Panchal07** [codecyclecommunity/learning-at-codecycle#1227]
### Purpose
- [x] To learn and practice Loops in Javascript
### Implement
- [x] Update issue (title, assignee, labels, projects, purpose, discovery, implement, measure)
- [x] Learn [Introduction](https://javascript.info/getting-started) 
- [x] Learn [Javascript Fundamentals](https://javascript.info/first-steps)
- [x] Practice each task available at the end of each section in Introduction and Javascript Fundamentals.
- [x] Create pyramid patterns using loops

### Measure
- [x] Validate basic concepts of Javascript loops
- [x] Patterns created with advance looping.
### Additional info

**Comment by Rahul-Panchal07** [comment]
@beingminimal please review! #1228

**Comment by beingminimal** [comment]
Approved. Close this task and continue with your learning journey.
