### ISSUE TITLE
Learn CSS upto Flex (000 to 009)

### ISSUE THREAD

**Issue by Prapti-Patel** [codecyclecommunity/learning-at-codecycle#1248]
### Purpose
- [x] To learn basics of CSS
### Implement
- [x] Update issue (title, assignee, labels, projects, purpose, discovery, implement, measure)
- [x] Learn 010 ([Grid](https://web.dev/learn/css/grid/))
### Measure
- [x] All concepts learned in this task should be clear and understood.

**Comment by Prapti-Patel** [comment]
@beingminimal please review.

**Comment by beingminimal** [comment]
Approved. Close this task and continue with your learning journey.
