### ISSUE TITLE
 Learn CSS Layout and logical properties

### ISSUE THREAD

**Issue by Prapti-Patel** [codecyclecommunity/learning-at-codecycle#1253]
### Purpose
- [x] To learn CSS Layout and logical properties
### Implement
- [x] Update issue (title, assignee, labels, projects, purpose, discovery, implement, measure)
- [x] [The fundamentals of CSS layout | Workshop](https://www.youtube.com/watch?v=yMEjLBKyvEg)
- [x] Learn 011 ([Logical Properties](https://web.dev/learn/css/logical-properties/)) to 019 ([Functions](https://web.dev/learn/css/functions/))```

```[tasklist]
### Measure
- [x] All concepts learned in this task should be clear and understood.
### Additional info

**Comment by Prapti-Patel** [comment]
@beingminimal Please review.

**Comment by beingminimal** [comment]
which units we should use for fonts

**Comment by Prapti-Patel** [comment]
@beingminimal We should use em, rem, px units for font

**Comment by beingminimal** [comment]
Approved. Close this task and continue with your learning journey.
