### ISSUE TITLE
yashpatel2920 | 01 Learn basics of JS

### ISSUE THREAD

**Issue by yashpatel2920** [codecyclecommunity/learning-at-codecycle#902]
### Purpose
- [x] To learn basisc of JS
### Implement
- [x] Update issue (title, assignee, labels, projects, purpose, discovery, implement, measure)
- [x] Complete beginner level courses to get basic knowledge about JS fundamentals.
### Measure
- [x] Basic understanding of JS

**Comment by yashpatel2920** [comment]
@beingminimal review sir.
#1221

**Comment by beingminimal** [comment]
Approved. Close this task and continue with your learning journey.
