### ISSUE TITLE
Learn basics of Javascript-01

### ISSUE THREAD

**Issue by Divya-Thakur01** [codecyclecommunity/learning-at-codecycle#964]
### Purpose
- [x] To learn basisc of JS
### Implement
- [x] Update issue (title, assignee, labels, projects, purpose, discovery, implement, measure)
- [x] Complete beginner level courses to get basic knowledge about JS fundamentals.
### Measure
- [x] Basic understanding of JS
### Additional info

**Comment by Divya-Thakur01** [comment]
@beingminimal please review it.

**Comment by beingminimal** [comment]
Approved. Close this task and continue with your learning journey.
